spring:
  application:
    name: mealpair

  # Java 25 가상 스레드 활성화 (성능 최적화)
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: qwer1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true