spring:
  config:
    activate:
      on-profile: prod

  datasource:
    # Docker Compose의 .env에서 주입됨
    url: ${SPRING_DATASOURCE_URL}
    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false